// <auto-generated />
using System;
using EnglishLearning.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishLearning.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407031154_AddGrammarKnowledgeGraph")]
    partial class AddGrammarKnowledgeGraph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BadgeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("badge_code");

                    b.Property<string>("BadgeIcon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("badge_icon");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("badge_name");

                    b.Property<string>("BadgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("badge_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RequirementJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirement_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BadgeCode")
                        .IsUnique();

                    b.ToTable("tb_badge", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Checkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("int")
                        .HasColumnName("bonus_points");

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("checkin_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int>("StreakDays")
                        .HasColumnType("int")
                        .HasColumnName("streak_days");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CheckinDate")
                        .IsUnique();

                    b.ToTable("tb_checkin", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.DailyChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChallengeDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("challenge_date");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("int")
                        .HasColumnName("coins_earned");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int")
                        .HasColumnName("correct_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("TimeUsedSeconds")
                        .HasColumnType("int")
                        .HasColumnName("time_used_seconds");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ChallengeDate")
                        .IsUnique();

                    b.ToTable("tb_daily_challenge", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.DailyChallengeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DailyChallengeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("daily_challenge_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<bool>("IsUncertain")
                        .HasColumnType("bit")
                        .HasColumnName("is_uncertain");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int")
                        .HasColumnName("question_order");

                    b.Property<int>("TimeUsedSeconds")
                        .HasColumnType("int")
                        .HasColumnName("time_used_seconds");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_answer");

                    b.HasKey("Id");

                    b.HasIndex("DailyChallengeId");

                    b.HasIndex("QuestionId");

                    b.ToTable("tb_daily_challenge_detail", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.GradeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Grade")
                        .HasColumnType("int")
                        .HasColumnName("grade");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("semester");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_name");

                    b.Property<int>("UnitNo")
                        .HasColumnType("int")
                        .HasColumnName("unit_no");

                    b.HasKey("Id");

                    b.HasIndex("Grade", "Semester", "UnitNo")
                        .IsUnique();

                    b.ToTable("tb_grade_unit", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Grammar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_json");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DependencyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("GradeUnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_unit_id");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int")
                        .HasColumnName("passing_score");

                    b.Property<Guid?>("PrerequisiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuizJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quiz_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("GradeUnitId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("tb_grammar", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.LearningProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("int")
                        .HasColumnName("attempts_count");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GradeUnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_unit_id");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_attempt_at");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GradeUnitId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ContentType", "ContentId");

                    b.ToTable("tb_learning_progress", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AnswerAnalysis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer_analysis");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasColumnName("difficulty");

                    b.Property<Guid>("GradeUnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_unit_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("KnowledgePoint")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("knowledge_point");

                    b.Property<string>("QuestionStem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_stem");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_type");

                    b.Property<string>("StemAudioUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stem_audio_url");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradeUnitId");

                    b.HasIndex("GradeUnitId", "IsActive", "Difficulty");

                    b.ToTable("tb_question", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audio_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("OptionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_content");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_key");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tb_question_option", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int")
                        .HasColumnName("grade_level");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("earned_at");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit")
                        .HasColumnName("is_new");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_user_badge", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("int")
                        .HasColumnName("current_exp");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int")
                        .HasColumnName("current_level");

                    b.Property<int>("ExpToNext")
                        .HasColumnType("int")
                        .HasColumnName("exp_to_next");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level_name");

                    b.Property<DateTime?>("LevelUpAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("level_up_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tb_user_level", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserPoints", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int")
                        .HasColumnName("balance_after");

                    b.Property<int>("ChangeAmount")
                        .HasColumnType("int")
                        .HasColumnName("change_amount");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("PointsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("points_type");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reference_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PointsType");

                    b.ToTable("tb_user_points", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int")
                        .HasColumnName("current_streak");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("LearningStyle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("learning_style");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("int")
                        .HasColumnName("max_streak");

                    b.Property<bool>("ParentNotifyEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("parent_notify_enabled");

                    b.Property<TimeSpan?>("PreferredStudyTime")
                        .HasColumnType("time")
                        .HasColumnName("preferred_study_time");

                    b.Property<int>("TotalLearningDays")
                        .HasColumnType("int")
                        .HasColumnName("total_learning_days");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tb_user_profile", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audio_url");

                    b.Property<string>("ExampleCn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("example_cn");

                    b.Property<string>("ExampleEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("example_en");

                    b.Property<Guid>("GradeUnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_unit_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("MeaningCn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meaning_cn");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("PhoneticUk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phonetic_uk");

                    b.Property<string>("PhoneticUs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phonetic_us");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("WordText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("word_text");

                    b.HasKey("Id");

                    b.HasIndex("GradeUnitId");

                    b.HasIndex("GradeUnitId", "SortOrder");

                    b.ToTable("tb_word", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.WrongQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer");

                    b.Property<string>("ErrorType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_type");

                    b.Property<DateTime>("FirstWrongAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("first_wrong_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastReviewAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_review_at");

                    b.Property<DateTime?>("MasteredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("mastered_at");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_review_at");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int")
                        .HasColumnName("review_count");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("review_status");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_answer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ReviewStatus");

                    b.ToTable("tb_wrong_question", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Checkin", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithMany("Checkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.DailyChallenge", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithMany("DailyChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.DailyChallengeDetail", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.DailyChallenge", "DailyChallenge")
                        .WithMany("Details")
                        .HasForeignKey("DailyChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishLearning.Domain.Entities.Question", "Question")
                        .WithMany("DailyChallengeDetails")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyChallenge");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Grammar", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.GradeUnit", "GradeUnit")
                        .WithMany("Grammars")
                        .HasForeignKey("GradeUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishLearning.Domain.Entities.Grammar", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId");

                    b.Navigation("GradeUnit");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.LearningProgress", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.GradeUnit", "GradeUnit")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("GradeUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Question", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.GradeUnit", "GradeUnit")
                        .WithMany("Questions")
                        .HasForeignKey("GradeUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeUnit");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserLevel", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithOne("Level")
                        .HasForeignKey("EnglishLearning.Domain.Entities.UserLevel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserPoints", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithMany("UserPoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EnglishLearning.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Word", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.GradeUnit", "GradeUnit")
                        .WithMany("Words")
                        .HasForeignKey("GradeUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeUnit");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.WrongQuestion", b =>
                {
                    b.HasOne("EnglishLearning.Domain.Entities.Question", "Question")
                        .WithMany("WrongQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishLearning.Domain.Entities.User", "User")
                        .WithMany("WrongQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.DailyChallenge", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.GradeUnit", b =>
                {
                    b.Navigation("Grammars");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Questions");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.Question", b =>
                {
                    b.Navigation("DailyChallengeDetails");

                    b.Navigation("Options");

                    b.Navigation("WrongQuestions");
                });

            modelBuilder.Entity("EnglishLearning.Domain.Entities.User", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("DailyChallenges");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Level");

                    b.Navigation("Profile");

                    b.Navigation("UserBadges");

                    b.Navigation("UserPoints");

                    b.Navigation("WrongQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
